default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  host: db
  password: postgres
  username: postgres

development:
  <<: *default
  database: app_development

test:
  <<: *default
  database: app_test

production:
  <<: *default
  username: myapp
  url: <%= ENV['DATABASE_URL'] %>
